GET https://49s7y6-3000.csb.app/api/auth/reminders HTTP/1.1

###

GET https://49s7y6-3000.csb.app/api/auth/reminders HTTP/1.1
X-Authorization: abc123

###

POST https://49s7y6-3000.csb.app/api/login HTTP/1.1
Content-Type: "application/json"

{
    "username":"Testeando",
    "password":"test123."
}


###